[package]
name = "port-forward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
uuid = "0.8"
tokio = "1.12.0"
rlua = "0.18.0"
